# Generated by Django 3.0.7 on 2020-07-07 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 7, 8, 59, 43, 593998)),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
    ]
