# Generated by Django 3.0.7 on 2020-07-14 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200713_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 12, 49, 15, 821047)),
        ),
    ]
