# Generated by Django 3.0.7 on 2020-07-07 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200707_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 7, 10, 39, 8, 250938)),
        ),
    ]
