# Generated by Django 3.0.7 on 2020-07-15 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200714_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 17, 52, 7, 566996)),
        ),
    ]
