# Generated by Django 3.0.7 on 2020-07-07 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200707_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_datetime',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 7, 11, 20, 44, 656327)),
        ),
    ]
